/* Jenkins declarative CD pipeline */

pipeline {
  agent { label 'slaveNode1'}

  parameters {
    booleanParam(name: 'autoApprove', defaultValue: false,
      description: 'Atomaticamente publicar el plan de terraform?')
    booleanParam(name: 'destroy', defaultValue: false,
      description: 'Destruir el plan de terraform')
  }
  environment {
    /* AWS credentials previosly setted on slave node */
    // AWS_ACCESS_KEY_ID
    // AWS_SECRET_ACCESS_KEY
  }

  stages {
    stage('Clean workspace') {
      steps { cleanWs() }
    }
    stage('Checkout') {
      steps {
        steps {
          dir("infra") {
            git branch: '${env.BRANCH_NAME}',
            url: 'git@github.com:axelPalmerin/robinfood-devops-test.git'
          }
        }
      }
    }

    stage('Plan') {
      steps {
        sh 'terraform init -input=false'
        sh "terraform plan -input=false -out tfplan"
        sh 'terraform show -no-color tfplan > tfplan.txt'
      }
    }

    stage('Approval') {
      /* Review plan and manual apply when Approval is False */
      when { expression { !params.autoApprove } }
      steps {
        script {
          def plan = readFile 'tfplan.txt'
          input message: "Apply Terraform plan?",
          parameters: [text(name: 'Plan', description: 'Review', defaultValue: plan)]
        }
      }
   }

    stage('Apply') {
      /* Apply plan when destroy is False */
      when { expression { !params.destroy } }
      steps {
        sh "terraform apply -input=false tfplan"
      }
    }

    stage('Destroy') {
      /* Destroy if flag is true */
      when { expression { params.destroy } }
      steps {
        sh "terraform destroy --auto-approve"
      }
    }
  }
}
